# docker-compose.yaml
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "80:80"
    networks: [appnet]
    depends_on: [backend]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "86:80"            # change to "86:3000" if your app listens on 3000
    environment:
      DB_HOST: database-1.c9meigac6f36.ap-south-1.rds.amazonaws.com
      DB_USERNAME: admin
      DB_PASSWORD: simon1234   # use your actual RDS password
      DB_NAME: test
      DB_PORT: "3306"
      # optional, if your code uses these:
      HOST: database-1.c9meigac6f36.ap-south-1.rds.amazonaws.com
      DB_USER: admin
    networks: [appnet]

networks:
  appnet:
    driver: bridge

